# vim: set ts=2 sw=2 et:
keys:
  - &pbor D45ECBD522E389A8A377925FB1392A8089E0A994
  - &rock 03985A107FED4BAC061E93D5E7AF1C3727A8DBF1

creation_rules:
  - path_regex: secrets/shared/[^/]+.yaml$
    key_groups:
      - pgp:
        - *pbor
        - *rock

  - path_regex: secrets/machines/rock/[^/]+.yaml$
    key_groups:
      - pgp:
        - *pbor
        - *rock
