# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/headless.nix")

    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-pc-ssd
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/909c762d-0ac8-4855-a306-eb395e515620";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0152-F946";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/c47c0995-31a1-4249-8c02-7678319fd1b0";}];

  hardware.enableRedistributableFirmware = true;
}
